### ISSUE TITLE
Columns don't line up properly in Matlab version of B Damage

### ISSUE THREAD

**Issue by JonnyCBB** [td93/B_Damage#1]
It's probably not a huge problem for now since I imagine this will not be such a problem when the Python version is finished but the column headers don't line up with the columns properly in the B_Damage text file (see image in the README). If you do get time then feel free to sort it out but otherwise I wouldn't worry about it unless a user specifically wants it sorted.

**Comment by td93** [comment]
Hey Jonny, yeah I was going to fix it with the move over to Python, and also reorder the additional columns to the right to a slightly more logical order :)
Thanks!
Tom

**Comment by JonnyCBB** [comment]
Ok that's cool. I'll leave this issue open since this specifically is about the MATLAB version and not the Python version. But as I mentioned before, there's no need to sort this unless a user really wants it sorted or if you begin to feel that you miss MATLAB :-P

**Comment by td93** [comment]
PARTIAL FIX: Things do now line up but the Element lies in the charge column, and charge data is by default absent.

**Comment by JonnyCBB** [comment]
That's not a problem. If you're happy that the columns line up then I would say that this issued is sorted and you can go ahead and close it. Great job ;)
