### ISSUE TITLE
Deleting old branch

### ISSUE THREAD

**Issue by kls93** [td93/B_Damage#13]
Dear All, 

Would it be OK if I delete the old branch (td93-patch-1) to avoid user confusion? I was then intending to release the current master branch, before creating a new branch to add in changes specific to CCP4 that will reduce the user-friendliness of the standalone program. Let me know if there will be any problems with this however.

Thanks very much for your help,
Kathryn

**Comment by td93** [comment]
Hi Kathryn,

That sounds like a good plan, I have deleted my old stale branch. It was only a single commit ahead, and that was in deprecated functionality anyway!

Tom
