### ISSUE TITLE
Bad interpreter

### ISSUE THREAD

**Issue by murpholinox** [td93/B_Damage#14]
```
[murpho0@eva03 rabdam]$ rabdam -f 5kxk.cif 
bash: /home/murpho0/Bins/ccp4/ccp4-7.0/bin/rabdam: /opt/xtal/ccp4-7.0-linux64/devbin/python: bad interpreter: No such file or directory
```
Indeed the is no such directory.

**Comment by kls93** [comment]
Hi, 

Unfortunately there is a problem with the RABDAM bang line in CCP4, which is preventing it from running. I will fix this soon (hopefully for the next CCP4 release), however in the meantime RABDAM should work if you clone it from GitHub or install the PyPi package.

Kathryn

**Comment by kls93** [comment]
Issue fixed in the latest CCP4 release.
