### ISSUE TITLE
Accuracy of B Damage Values

### ISSUE THREAD

**Issue by JonnyCBB** [td93/B_Damage#9]
I think that the number of decimal places to which we report the B damage values is too high. If I remember rightly the figures in the PDB files are reported to 3 decimal places so I'm inclined to not report more than 3 decimal places for the derived B damage values.   

What do you think?

**Comment by kls93** [comment]
Fixed - html and csv outputs now report average Bfactor and Bdamage values to 2dp, all other floats to 3dp

**Comment by JonnyCBB** [comment]
Fantastic :+1:

**Comment by td93** [comment]
Careful about usage of accuracy and precision :P, hopefully the accuracy is unchanged, but the precision reported is lower!

**Comment by kls93** [comment]
Values reported in html output are to 2/3dp, but values used to calculate e.g. the histogram are same as before

**Comment by JonnyCBB** [comment]
Yes I should've titled this **Precision** rather than **Accuracy** :P
